# Generated by Django 4.1.7 on 2023-03-11 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_profile_cover'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='restaurant',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
