# Generated by Django 4.1.7 on 2023-03-11 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chef', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Chef',
        ),
    ]
