# Generated by Django 4.1.7 on 2023-05-08 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chef', '0002_delete_chef'),
    ]

    operations = [
        migrations.CreateModel(
            name='Modules',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_1', models.CharField(blank=True, max_length=250, null=True)),
                ('week_2', models.CharField(blank=True, max_length=250, null=True)),
                ('week_3', models.CharField(blank=True, max_length=250, null=True)),
                ('week_4', models.CharField(blank=True, max_length=250, null=True)),
                ('week_5', models.CharField(blank=True, max_length=250, null=True)),
                ('week_6', models.CharField(blank=True, max_length=250, null=True)),
            ],
        ),
    ]
