# Generated by Django 4.1.7 on 2023-05-08 13:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chef', '0003_modules'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='modules',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='chef.modules'),
        ),
    ]
