# Generated by Django 4.1.7 on 2023-05-08 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chef', '0004_course_modules'),
    ]

    operations = [
        migrations.AddField(
            model_name='modules',
            name='video_link',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
