# Generated by Django 4.1.7 on 2023-05-08 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chef', '0005_modules_video_link'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='modules',
            new_name='module',
        ),
    ]
