# Generated by Django 4.1.7 on 2023-05-08 15:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chef', '0006_rename_modules_course_module'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='module',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='chef.modules'),
        ),
    ]
