# Generated by Django 4.1.7 on 2023-05-12 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chef', '0007_alter_course_module'),
    ]

    operations = [
        migrations.AddField(
            model_name='modules',
            name='detail_1',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='modules',
            name='detail_2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='modules',
            name='detail_3',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='modules',
            name='detail_4',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='modules',
            name='detail_5',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='modules',
            name='detail_6',
            field=models.TextField(blank=True, null=True),
        ),
    ]
